unbind r
bind r source-file  ~/.tmux.conf

# Start windows and panes at 1
set -g base-index 1
set -g pane-base-index 1
set -s escape-time 0
set -g prefix C-a
set -g mouse on

set -g focus-events on
set -g allow-passthrough on
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

# Inner panel vim movement keys 
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# pane borders (only render when 2+ panes exist)
set -g pane-border-style "fg=colour240"
set -g pane-active-border-style "fg=#5ef1ff"

# window status theme
set -g window-status-format " #[fg=colour245] ◯ #I - #W "
set -g window-status-current-format " #[fg=#5ef1ff] ◎ #I - #W "
set -g status-bg "#1a1b26"

set -g message-style "bg=#5ef1ff,fg=#1a1b26,bold"

# Rename the tabs
set-option -g automatic-rename on
set-option -g renumber-windows on
set-option -g automatic-rename-format '#{b:pane_current_path}'

# Status bar postion
set-option -g status-position bottom
set-option -g status-justify centre
set-option -g status-left ''
set-option -g status-right ''

